package com.panoprogramowanie.boilingfrogs.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import java.util.ArrayList;
import java.util.List;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.internal.SqlUtils;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SPEECH_SLOT".
*/
public class SpeechSlotDao extends AbstractDao<SpeechSlot, Long> {

    public static final String TABLENAME = "SPEECH_SLOT";

    /**
     * Properties of entity SpeechSlot.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property TimeLabel = new Property(1, String.class, "timeLabel", false, "TIME_LABEL");
        public final static Property FavoriteSpeechId = new Property(2, Long.class, "favoriteSpeechId", false, "FAVORITE_SPEECH_ID");
    };

    private DaoSession daoSession;


    public SpeechSlotDao(DaoConfig config) {
        super(config);
    }
    
    public SpeechSlotDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SPEECH_SLOT\" (" + //
                "\"ID\" INTEGER PRIMARY KEY ," + // 0: id
                "\"TIME_LABEL\" TEXT," + // 1: timeLabel
                "\"FAVORITE_SPEECH_ID\" INTEGER);"); // 2: favoriteSpeechId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SPEECH_SLOT\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, SpeechSlot entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String timeLabel = entity.getTimeLabel();
        if (timeLabel != null) {
            stmt.bindString(2, timeLabel);
        }
 
        Long favoriteSpeechId = entity.getFavoriteSpeechId();
        if (favoriteSpeechId != null) {
            stmt.bindLong(3, favoriteSpeechId);
        }
    }

    @Override
    protected void attachEntity(SpeechSlot entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public SpeechSlot readEntity(Cursor cursor, int offset) {
        SpeechSlot entity = new SpeechSlot( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // timeLabel
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // favoriteSpeechId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, SpeechSlot entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTimeLabel(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setFavoriteSpeechId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(SpeechSlot entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(SpeechSlot entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getSpeechDao().getAllColumns());
            builder.append(" FROM SPEECH_SLOT T");
            builder.append(" LEFT JOIN SPEECH T0 ON T.\"FAVORITE_SPEECH_ID\"=T0.\"ID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected SpeechSlot loadCurrentDeep(Cursor cursor, boolean lock) {
        SpeechSlot entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Speech favoriteSpeech = loadCurrentOther(daoSession.getSpeechDao(), cursor, offset);
        entity.setFavoriteSpeech(favoriteSpeech);

        return entity;    
    }

    public SpeechSlot loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<SpeechSlot> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<SpeechSlot> list = new ArrayList<SpeechSlot>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<SpeechSlot> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<SpeechSlot> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
